site_name: 'Centre of Excellence (Draft)'
site_url: https://data-to-insight.github.io/centre-of-excellence # do we want this or another here? 
repo_url: https://github.com/data-to-insight/centre-of-excellence
docs_dir: docs

theme:
  name: material
  language: en
  features:
    - navigation.sections   # grp sections left nav
    - navigation.indexes    # collapse sub items (see appendices) 
    - navigation.top
    - content.code.copy
    - toc.follow
    - navigation.instant    # im[prove transitions

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - toc:
      permalink: true
nav:
  - 'How to use this document': index.md

  - 'Imagining a Centre of Excellence':
    - 'Overview': imagining-a-centre-of-excellence/index.md
    - 'A case for change': imagining-a-centre-of-excellence/a-case-for-change.md
    - 'Our invitation': imagining-a-centre-of-excellence/our-invitation.md
    - 'Clear opportunities': imagining-a-centre-of-excellence/clear-opportunities.md

  - 'How our system works': how-our-system-works/index.md
  - 'Possible mechanisms for change': possible-mechanisms-for-change/index.md
  - 'Models for delivery': models-for-delivery/index.md
  - 'Engagement opportunities': engagement-opportunities/index.md

  - 'Suggest a Change': suggestions.md # anon feedback / suggestion form

  - 'Appendices':                          # collapsible grps
    - 'Appendix 1: More on how our system works':
      - 'Overview': appendix-1-more-on-how-our-system-works/index.md
      - 'Context': appendix-1-more-on-how-our-system-works/context.md
      - 'Status': appendix-1-more-on-how-our-system-works/status.md
      - 'Value': appendix-1-more-on-how-our-system-works/value.md
      - 'Quality': appendix-1-more-on-how-our-system-works/quality.md
      - 'Cost': appendix-1-more-on-how-our-system-works/cost.md

    - 'Appendix 2: More on possible mechanisms for change':
      - 'Overview': appendix-2-more-on-possible-mechanisms-for-change/index.md
      - 'Data tool collaboration': appendix-2-more-on-possible-mechanisms-for-change/data-tool-collaboration.md
      - 'Improving data quality': appendix-2-more-on-possible-mechanisms-for-change/improving-data-quality.md
      - 'Facilitating information sharing': appendix-2-more-on-possible-mechanisms-for-change/facilitating-information-sharing.md
      - 'Making sense of case management systems': appendix-2-more-on-possible-mechanisms-for-change/making-sense-of-case-management-systems.md
      - 'Making sense of AI, RPA, and other advanced and integrative software': appendix-2-more-on-possible-mechanisms-for-change/making-sense-of-ai-rpa-and-other-advanced-and-integrative-software.md
      - 'Influencing technology markets': appendix-2-more-on-possible-mechanisms-for-change/influencing-technology-markets.md
      - 'Curating technical standards': appendix-2-more-on-possible-mechanisms-for-change/curating-technical-standards.md
      - 'Advocacy across internal hierarchies': appendix-2-more-on-possible-mechanisms-for-change/advocacy-across-internal-hierarchies.md
      - 'Supporting professional development': appendix-2-more-on-possible-mechanisms-for-change/supporting-professional-development.md
      - 'Helping leadership to expect excellence': appendix-2-more-on-possible-mechanisms-for-change/helping-leadership-to-expect-excellence.md
      - 'Redefining cross-sector collaboration': appendix-2-more-on-possible-mechanisms-for-change/redefining-cross-sector-collaboration.md
      - 'Responding to large-scale change': appendix-2-more-on-possible-mechanisms-for-change/responding-to-large-scale-change.md
      - 'Discovering what works': appendix-2-more-on-possible-mechanisms-for-change/discovering-what-works.md

    - 'Appendix 3: More on models for delivery': appendix-3-more-on-models-for-delivery/index.md
    - 'Appendix 4: Reference projects': appendix-4-reference-projects/index.md
