name: Feedback / Ticket
description: Share feedback or request related to docs/site
title: "Feedback: "
labels: ["feedbaclk", "docs"]
assignees: []
body:
  - type: input
    id: page
    attributes:
      label: Page URL
      description: Auto-filled from docs button
      placeholder: "https://…"
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Description of feedback or problem
      placeholder: "Feedback/suggestion or issue"
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Details / context
      description: Add context, examples, or screenshots
  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - Content
        - Navigation / IA
        - Accessibility
        - Visual / UI
        - Performance
        - Other
